site_name: Web Storage for Angular
site_description: Angular services for interacting with the Web Storage, implemented in TypeScript.
site_author: Cédric Belin - cedric@belin.io
site_url: https://dev.belin.io/ngx-webstorage.js

docs_dir: ../doc
site_dir: ../web

repo_name: GitHub
repo_url: https://github.com/cedx/ngx-webstorage.js
edit_uri: ''

copyright: Copyright &copy; 2017 - 2020 Cédric Belin
google_analytics:
  - !!python/object/apply:os.getenv [GOOGLE_ANALYTICS_ID]
  - auto

extra:
  social:
    - {type: globe, link: 'https://belin.io'}
    - {type: github, link: 'https://github.com/cedx'}
    - {type: twitter, link: 'https://twitter.com/cedxbelin'}
    - {type: linkedin, link: 'https://linkedin.com/in/cedxbelin'}

markdown_extensions:
  - admonition
  - codehilite

nav:
  - Overview: index.md
  - Installation: installation.md
  - Usage:
      - Programming interface: usage/api.md
      - Iteration: usage/iteration.md
      - Events: usage/events.md
  - About:
      - Changelog: about/changelog.md
      - License: about/license.md
      - See also: about/see_also.md

theme:
  name: material
  favicon: img/favicon.ico
  palette: {primary: blue, accent: red}
